insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (1, 'Kovacek LLC', '19', '2011-04-28');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (2, 'Kertzmann-Kris', '39', '2021-11-06');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (3, 'Price-Hayes', '1', '2024-04-12');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (4, 'Bradtke and Sons', '34', '2001-11-27');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (5, 'Crona-McLaughlin', '48', '2004-11-27');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (6, 'Haley, Carter and O''Reilly', '10', '2017-10-27');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (7, 'Zemlak Group', '17', '2005-12-10');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (8, 'Murazik, Hessel and Labadie', '13', '2016-11-06');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (9, 'Halvorson Group', '43', '2003-04-21');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (10, 'Balistreri-Stoltenberg', '9', '2023-06-10');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (11, 'Jones-Koss', '45', '2002-10-08');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (12, 'Simonis LLC', '18', '2006-05-25');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (13, 'Stracke-Larkin', '8', '2019-05-31');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (14, 'Reinger, Fahey and Schultz', '29', '2019-07-07');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (15, 'Ankunding, Larson and Stokes', '35', '2000-08-22');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (16, 'Denesik-Kulas', '4', '2006-11-05');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (17, 'Williamson-Leannon', '40', '2015-12-07');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (18, 'Lubowitz, Weber and Greenfelder', '3', '2023-06-04');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (19, 'Volkman and Sons', '36', '2011-10-13');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (20, 'Marvin, Bernier and Lubowitz', '47', '2003-06-10');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (21, 'Turcotte, Hettinger and McDermott', '28', '2012-04-28');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (22, 'Quigley, Lueilwitz and Spencer', '6', '2002-03-07');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (23, 'Robel-Welch', '5', '2023-04-03');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (24, 'Price-Herman', '30', '2021-04-29');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (25, 'Goldner and Sons', '46', '2001-04-14');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (26, 'Carter, Langworth and Schaden', '20', '2006-01-03');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (27, 'Johnson-Oberbrunner', '2', '2015-03-29');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (28, 'Kiehn-Kassulke', '27', '2001-10-25');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (29, 'Welch LLC', '49', '2008-06-01');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (30, 'Hayes LLC', '23', '2003-09-08');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (31, 'Yundt and Sons', '38', '2016-10-25');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (32, 'Johnston-Klocko', '11', '2016-08-08');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (33, 'Hickle-Brown', '37', '2018-06-08');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (34, 'Schmidt Group', '14', '2024-02-16');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (35, 'Terry, Bosco and D''Amore', '26', '2021-02-12');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (36, 'Smith, Shanahan and Nienow', '12', '2009-04-19');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (37, 'Zemlak LLC', '33', '2022-10-19');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (38, 'Schiller, Torp and Osinski', '44', '2008-02-21');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (39, 'Lindgren, Parker and Auer', '15', '2023-12-08');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (40, 'Torphy, Gusikowski and Pouros', '32', '2022-11-17');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (41, 'Johns-Goldner', '22', '2000-04-01');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (42, 'Jacobson LLC', '7', '2019-09-04');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (43, 'Nitzsche-Bartoletti', '31', '2001-03-16');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (44, 'Cassin Inc', '41', '2013-08-24');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (45, 'Bauch, Hirthe and Dietrich', '50', '2006-03-16');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (46, 'Dare and Sons', '24', '2000-04-11');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (47, 'McCullough Group', '25', '2003-06-13');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (48, 'Kuhic-Schimmel', '21', '2012-02-02');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (49, 'Adams-Prohaska', '16', '2020-02-14');
insert into groups (GroupID, GroupName, CreatedBy , DateAdded ) values (50, 'Bednar-Kulas', '42', '2014-11-08');
